name: Build and Push Springboot Application on Github Actions 
# Write on which event it should be triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# What jobs to be executed on those events
jobs:
  build:
    runs-on: ubuntu-latest
    # Write steps in a list each - indicates a list item
    #  Here first step is the copying current code in a ubuntu runner on github servers
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
    # Next step is to set up JDK in that runner as it doesnt have any environment to run and build our code
      - name: Set Up JDK 17
        uses: actions/setup-java@v5
        with: 
            distribution: 'temurin'
            java-version: 17

      - name: Test the Unit Tests 
        run: mvn -B test --file pom.xml

      - name: Package and build
    #   Use pip  to run multiple cmds . For this u can also write it in a single cmd mvn -B clean package
        run: | 
            mvn clean 
            mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESSTOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/incubyte-string-calculator-tdd-kata:${{ github.run_number }}
          file: ./Dockerfile